version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Map container's port 80 to host's port 80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

