name: Upload Build to Hostinger

on:
  push:
    branches:
      - main

jobs:
  upload-build:
    runs-on: ubuntu-latest

    env:
      FTP_SERVER: ${{ secrets.FTP_SERVER }}
      FTP_USER: ${{ secrets.FTP_USER }}
      FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      FTP_PORT: 21
      LOCAL_DIR: "ijlalkhan/build"
      REMOTE_DIR: "/public_html"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install lftp
      run: |
        sudo apt-get update
        sudo apt-get install lftp -y

    - name: Upload build folder contents to Hostinger using lftp
      run: |
        lftp -e "set ssl:verify-certificate no; open -u $FTP_USER,$FTP_PASSWORD -p $FTP_PORT $FTP_SERVER; mirror --reverse --delete --verbose $LOCAL_DIR $REMOTE_DIR; bye"
